name: Build DCS Mission

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - README.md
      - dummy.miz
      - appveyor.yml
      
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment version
        id: inc_version
        run: |
          VERSION="${{ steps.read_version.outputs.version }}"
          PREFIX=$(echo $VERSION | cut -d'-' -f1)
          MAJOR=$(echo $VERSION | cut -d'-' -f2 | cut -d'.' -f1)
          MINOR=$(echo $VERSION | cut -d'-' -f2 | cut -d'.' -f2)
          PATCH=$(echo $VERSION | cut -d'-' -f2 | cut -d'.' -f3)
          BUILD=$(echo $VERSION | cut -d'-' -f2 | cut -d'.' -f4)
          
          NEXT=$((BUILD + 1))
          NEW_VERSION="${PREFIX}-${MAJOR}.${MINOR}.${PATCH}.${NEXT}"
          echo $NEW_VERSION > version.txt
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit updated version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version.txt
          git commit -m "Version bump to ${{ steps.inc_version.outputs.new_version }}"
          git push

      - name: Create .miz file
        run: |
          zip -r ${{ steps.inc_version.outputs.new_version }}.miz . \
            -x ".github/*" \
            -x "*.git*" \
            -x "README.md" \
            -x "dummy.miz" \
            -x "appveyor.yml"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DCS-Mission-${{ steps.inc_version.outputs.new_version }}
          path: ${{ steps.inc_version.outputs.new_version }}.miz
